---
title: "WI_Mayer_replication"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the Combined Ward data file
```{r}
wi_data <- read.csv(file.choose())
print(wi_data)

```

## Drop uncontested races and a few problematic data points (area for review)
```{r}
wi_data <- wi_data[!(wi_data$contested_1=="0"),]
wi_data <- wi_data[-which(is.na(wi_data$persons_18)),]
wi_data <- wi_data[!(wi_data$WSAREP12=="0"),]
print(wi_data)

```

## Make county factor variables ensuring Dunn county is the baseline. Run the regression and plot predicted vs. actual
```{r}
wi_data$county.f <- factor(wi_data$county)

contrasts(wi_data$county.f) <- contr.treatment(72, base = 17)
rmodel <- lm(WSAREP12 ~ total_vep + c_black_vep + hisp_vep + PREDEM12 + PREREP12 + dem_incum + rep_incum + county.f, data = wi_data)
summary(rmodel)

rootmse <- function(sm)
    sqrt(mean(sm$residual^2))
rootmse(rmodel)


setwd("~/")
getwd()
png(filename = "RepWardGroupRegression.png")

plot(wi_data$WSAREP12, fitted.values(rmodel), xlab = "Actual Republican Assembly Votes", ylab = "Predicted Republican Assembly Votes")
fit = lm(fitted.values(rmodel)~wi_data$WSAREP12)
abline(fit, col = "red")
dev.off()

```

## Stepwise Selection of Variables
```{r}
rmodel <- lm(WSAREP12 ~ total_vep + c_black_vep + hisp_vep + PREDEM12 + PREREP12 + dem_incum + rep_incum +EC04+HC04+ED08+TR07, data = wi_data)
summary(rmodel)
library(olsrr)
ols_step_all_possible(rmodel)
ols_step_both_p(rmodel)
```